"""Paper table generator. NO TRAINING, NO GPU, NO HAND-TYPED NUMBERS.

Every number in paper/*.md must trace to a `reports/*.json` field read by
this script -- never hand-transcribed. Written 2026-08-06 because paper/ was
built by hand-transcription earlier in this project (see paper/README.md's
own "transcribed from reports/ only" framing) and the A4 baseline it cites
has already moved twice since (old runs/sweep_a4 -> unpinned
runs/a4_checkpointed -> whatever item 5's pinned-085 verdict lands on) --
each move silently staled the hand-written numbers until someone re-read
reports/ and re-typed them. This script exists so "re-generate paper/" is
`python scripts/46_generate_paper.py`, not a manual re-transcription pass.

SCOPE, HONESTLY STATED. Only `paper/03_gastronet.md` (the section directly
downstream of the A4 baseline this whole remediation is about) is fully
implemented as a generator in this first pass. The other eight files
(00, 01, 02, 04, 05, 06, 99, README) remain the ORIGINAL hand-transcribed
versions from earlier in the project -- this script does NOT touch them, and
they should NOT be assumed current relative to whatever reports/ says today.
Converting each to its own generate_NN_*() function is the obvious next
increment; the pattern established by generate_03_gastronet() below (read
reports/*.json fields, render markdown, cite the exact source field per
table) is meant to be copied, not reinvented, when that work happens.

    python scripts/46_generate_paper.py            # regenerate 03 only
    python scripts/46_generate_paper.py --section 03
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT_DIR = os.path.join(REPO_ROOT, "reports")
PAPER_DIR = os.path.join(REPO_ROOT, "paper")


def _load_json(name: str) -> dict:
    path = os.path.join(REPORT_DIR, name)
    with open(path) as fh:
        return json.load(fh)


def _load_json_optional(name: str):
    path = os.path.join(REPORT_DIR, name)
    if not os.path.exists(path):
        return None
    with open(path) as fh:
        return json.load(fh)


def fmt(x, p=4):
    return "n/a" if x is None else f"{x:.{p}f}"


FIELDS = ("fpr_at_90_recall", "fpr_prior_equalised", "fpr_asymmetry",
         "fpr_center_1", "fpr_center_2", "roc_auc", "pauc_15_std",
         "pauc_15_raw", "centre_auc_negatives")
LABELS = {
    "fpr_at_90_recall": "FPR@90R",
    "fpr_prior_equalised": "FPR@90R, prior-equalised",
    "fpr_asymmetry": "centre asymmetry (c1 - c2)",
    "fpr_center_1": "FPR@90R (center_1)",
    "fpr_center_2": "FPR@90R (center_2)",
    "roc_auc": "ROC-AUC",
    "pauc_15_std": "pAUC[0,0.15] (McClish)",
    "pauc_15_raw": "pAUC[0,0.15] (area/0.15)",
    "centre_auc_negatives": "AUC(logit -> centre, neg)",
}


def _g0_pooled():
    """G0 (RN50, ImageNet init) is NOT in reports/gastronet.json's "results"
    dict -- that dict is populated only for 30_gastronet.py's original
    BACKBONES list (G1/G2/G3); G0 was added later by the separate
    scripts/33_g0_control.py, which writes gastronet.md directly and never
    touches gastronet.json. So G0's pooled figures are computed fresh here,
    the same way scripts/44_pinned_arm_chain.py's compute_g0_loco_report()
    already does -- not read from a field that does not exist."""
    for p in (REPO_ROOT, os.path.join(REPO_ROOT, "scripts")):
        if p not in sys.path:
            sys.path.insert(0, p)
    import importlib.util
    import pandas as pd
    spec = importlib.util.spec_from_file_location(
        "_gn", os.path.join(REPO_ROOT, "scripts", "30_gastronet.py"))
    GN = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(GN)
    manifest = pd.read_csv(os.path.join(REPO_ROOT, "manifests", "rare25_folds_v2.csv"))
    g0_dir = os.path.join(REPO_ROOT, "runs", "g0_rn50_imagenet")
    if not os.path.isdir(g0_dir):
        return None
    return GN.analyse("runs/g0_rn50_imagenet", manifest)


def generate_03_gastronet() -> str:
    gj = _load_json("gastronet.json")
    rule2 = _load_json_optional("g3_loco_rule2.json")
    a4_ref = gj["reference_a4"]
    results = gj["results"]
    g0_loco = _load_json_optional("g0_loco.json")
    pinned = _load_json_optional("a4_pinned085_verdict.json")
    g0_pooled = _g0_pooled()

    L = []
    A = L.append
    A("# GastroNet / DINOv2 Ensemble Diversity Members (G0-G3)")
    A("")
    A(f"Source: `reports/gastronet.json`, `reports/g3_loco_rule2.json`"
     + (", `reports/g0_loco.json`" if g0_loco else "")
     + (", `reports/a4_pinned085_verdict.json`" if pinned else "")
     + f". Regenerated by `scripts/46_generate_paper.py` on "
       f"{time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())} -- every "
       f"number below is read from those files at generation time, none "
       f"hand-typed.")
    A("")

    if pinned:
        A(f"**A4 baseline status: {pinned['conclusion']}** "
         f"(pinned-085 FPR@90R {fmt(pinned['pinned_fpr_at_90_recall'])} vs "
         f"old {fmt(pinned['old_fpr'])} / unpinned {fmt(pinned['unpinned_fpr'])}). "
         f"Every A4 figure below is the CURRENT reports/gastronet.json "
         f"reference; re-run this script if that changes again.")
    else:
        A("**A4 baseline status: item 5 (pinned-085 isolation arm) has not "
         "resolved yet.** Every A4 figure below is `reports/gastronet.json`'s "
         "CURRENT reference (`runs/a4_checkpointed`, unpinned, current code) "
         "-- this is provisional and will move again once item 5 lands. "
         "Re-run this script after it does.")
    A("")

    A("## Status")
    A("")
    A("Table 1: Backbone completion status.")
    A("")
    A("| backbone | status |")
    A("|---|---|")
    for key in ("g1_rn50_swsl", "g2_vitb_dinov2", "g3_rn50_gastronet"):
        st = results[key]["status"]
        A(f"| {results[key]['label']} | {st['done']}/{st['total']} |")
    A("")

    if rule2 and rule2.get("accept") is not None:
        A("## G3 LOCO -- does the SWSL-ablated control earn a slot")
        A("")
        A("Table 2: Rule 2 (control = A4), from `reports/g3_loco_rule2.json`.")
        A("")
        A("| clause | result |")
        A("|---|---|")
        A(f"| 1. Both LOCO directions improve over A4 | "
         f"{'**yes**' if rule2['both_directions_improve'] else '**no**'} |")
        A(f"| 2. At least one beyond conservative bar | "
         f"{'**yes**' if rule2['at_least_one_beyond_bar'] else '**no**'} |")
        asym = rule2["asymmetry"]
        A(f"| 3. Centre asymmetry reduced vs A4 (A4={fmt(asym['a4'])}, "
         f"G3={fmt(asym['g3'])}, bar={fmt(asym['bar'])}) | "
         f"{'**yes**' if asym['reduced_beyond_bar'] else '**no**'} |")
        A(f"| 4. VETO | "
         f"{'TRIGGERED' if rule2['veto']['triggered'] else 'not triggered'} |")
        A(f"| **Verdict (control = A4)** | "
         f"**{'ACCEPTED' if rule2['accept'] else 'REJECTED'}** |")
        A("")

    A("## G0 control -- isolating GastroNet pretraining at fixed capacity")
    A("")
    if g0_pooled:
        g0v = g0_pooled["k5"]["fpr_at_90_recall"]
        g3v = results["g3_rn50_gastronet"]["pooled"]["k5"]["fpr_at_90_recall"]
        a4v = a4_ref["k5"]["fpr_at_90_recall"]
        A(f"**G0 (RN50/ImageNet) {fmt(g0v)}, G3 (RN50/GastroNet) {fmt(g3v)}, "
         f"A4 (ConvNeXt/ImageNet) {fmt(a4v)} -- RN50-on-ImageNet is "
         f"{g0v/a4v:.1f}x WORSE than ConvNeXt-on-ImageNet, ruling out "
         f"capacity as the explanation for G3's strength and attributing it "
         f"to pretraining.**")
        A("")
        A("Table 3: G3 vs G0 vs A4, pooled OOF k=5.")
        A("")
        A("| metric | A4 | G3 | G0 | G3 minus G0 |")
        A("|---|---|---|---|---|")
        for f in FIELDS:
            av = a4_ref["k5"][f]
            g3f = results["g3_rn50_gastronet"]["pooled"]["k5"][f]
            g0f = g0_pooled["k5"][f]
            A(f"| {LABELS[f]} | {fmt(av)} | {fmt(g3f)} | {fmt(g0f)} | "
             f"{g3f - g0f:+.4f} |")
        A("")
    else:
        A("_runs/g0_rn50_imagenet not found on disk -- section incomplete, "
         "not fabricated._")
        A("")

    if g0_loco:
        A("## G0 LOCO -- does GastroNet pretraining's advantage survive an unseen centre")
        A("")
        A(f"**{g0_loco['headline_question']}**")
        A("")
        A(f"Pooled G3 minus G0: {fmt(g0_loco['pooled_g3_minus_g0'])}.")
        A("")
        A("Table 4: G3 minus G0, per LOCO direction.")
        A("")
        A("| direction | G3 | G0 | G3 minus G0 | resolvable? |")
        A("|---|---|---|---|---|")
        for c in ("1", "2"):
            pc = g0_loco["per_centre"][c] if c in g0_loco["per_centre"] else g0_loco["per_centre"][int(c)]
            A(f"| holdout_center_{c} | {fmt(pc['g3_k5_fpr'])} | "
             f"{fmt(pc['g0_k5_fpr'])} | {pc['g3_minus_g0']:+.4f} | "
             f"{'**yes**' if pc['resolvable'] else 'no'} |")
        A("")
        A(f"**{g0_loco['conclusion']}**")
        A("")
    else:
        A("## G0 LOCO")
        A("")
        A("_Not yet run. `reports/g0_loco.json` absent -- queued behind "
         "item 5 (see `scripts/44_pinned_arm_chain.py`)._")
        A("")

    for key, label in (("g1_rn50_swsl", "G1"), ("g2_vitb_dinov2", "G2"),
                       ("g3_rn50_gastronet", "G3")):
        r = results[key]
        if not r["status"]["complete"]:
            continue
        A(f"## {label} vs A4 (current baseline)")
        A("")
        A(f"Table: {label} pooled-OOF vs current A4 reference.")
        A("")
        A("| metric | A4 (current) | " + label + " | delta | bar | resolvable? |")
        A("|---|---|---|---|---|---|")
        for f in FIELDS:
            av = a4_ref["k5"][f]
            gv = r["pooled"]["k5"][f]
            bar = max(a4_ref["loo4"][f]["iqr"], r["pooled"]["loo4"][f]["iqr"])
            d = av - gv
            A(f"| {LABELS[f]} | {fmt(av)} | {fmt(gv)} | {d:+.4f} | {fmt(bar)} | "
             f"{'**yes**' if abs(d) > bar else 'no'} |")
        A("")

    return "\n".join(L) + "\n"


GENERATORS = {
    "03": ("03_gastronet.md", generate_03_gastronet),
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--section", default=None,
                    help="only regenerate this section (e.g. 03); default: all implemented")
    args = ap.parse_args()

    sections = [args.section] if args.section else list(GENERATORS.keys())
    os.makedirs(PAPER_DIR, exist_ok=True)
    for key in sections:
        if key not in GENERATORS:
            print(f"no generator for section {key!r} yet -- see this "
                 f"script's module docstring for what remains hand-transcribed",
                 file=sys.stderr)
            continue
        filename, fn = GENERATORS[key]
        content = fn()
        path = os.path.join(PAPER_DIR, filename)
        with open(path, "w") as fh:
            fh.write(content)
        print(f"written: {path}")

    not_covered = [f for f in os.listdir(PAPER_DIR)
                  if f.endswith(".md") and f not in {v[0] for v in GENERATORS.values()}
                  and f != "README.md"]
    if not_covered:
        print(f"\nSTILL HAND-TRANSCRIBED, not regenerated by this script: "
             f"{sorted(not_covered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
